#!/usr/bin/env python3
"""
Generate golden parity vectors from the Python reference implementation.

The browser port in frontend/src/lib must reproduce these byte for byte,
otherwise melodies encoded by earlier versions stop decoding correctly.

Usage:
    python golden_vectors.py
"""

import json
import os
from typing import List, Dict

from cipher import (
    MODES,
    MusicCipher,
    build_scale,
    safe_vowel_degrees,
)
from music_converter import MusicConverter

OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "frontend",
    "src",
    "lib",
    "__fixtures__",
    "goldenVectors.json",
)

# Texts chosen to exercise every branch: vowels, consonants, capitals,
# spaces, punctuation, rare letters, digits and non-ascii input.
TEXTS = [
    "HI",
    "HELLO WORLD",
    "GOOD MORNING.",
    "Python",
    "MUSIC",
    "The quick brown fox jumps over the lazy dog!",
    "Jazz, xylophone & quartz?",
    "a e i o u A E I O U",
    "Mixed CASE with 123 digits",
    "  leading and trailing  ",
    "naive cafe resume",
]

KEYS = ["", "hunter2", "a much longer key phrase with spaces"]

TONICS = ["C", "D", "F#", "A#", "B"]


def build_cases() -> List[Dict]:
    converter = MusicConverter()
    cases = []

    for text in TEXTS:
        for key in KEYS:
            for tonic in TONICS:
                for mode in MODES:
                    cipher = MusicCipher(key, tonic, mode)

                    notes = cipher.text_to_notes(text)
                    sequence_text = cipher.format_note_sequence(notes)
                    parsed = cipher.parse_note_sequence(sequence_text)

                    cases.append({
                        "text": text,
                        "key": key,
                        "tonic": tonic,
                        "mode": mode,
                        "scale": cipher.scale,
                        "notes": notes,
                        "note_sequence_text": sequence_text,
                        "parsed_sequence": parsed,
                        "decrypted_from_notes": cipher.notes_to_text(notes),
                        "decrypted_from_parsed": cipher.notes_to_text(parsed),
                        "abc_notation": converter.notes_to_abc_notation(notes),
                        "web_audio": json.loads(
                            converter.generate_web_audio_json(notes)
                        ),
                        "web_audio_harmonic": json.loads(
                            converter.generate_harmonic_web_audio_json(notes)
                        ),
                    })

    return cases


def build_scale_cases() -> List[Dict]:
    """Scale and vowel-degree tables on their own, so a mismatch points
    straight at the key building rather than at the cipher as a whole."""
    cases = []
    for tonic in TONICS:
        for mode in MODES:
            cases.append({
                "tonic": tonic,
                "mode": mode,
                "scale": build_scale(tonic, mode),
                "safe_vowel_degrees": safe_vowel_degrees(mode),
            })
    return cases


def main() -> None:
    payload = {
        "note": "Generated by backend/golden_vectors.py - do not edit by hand",
        "scales": build_scale_cases(),
        "cases": build_cases(),
    }

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    print(f"Wrote {len(payload['cases'])} cases to {os.path.normpath(OUTPUT_PATH)}")


if __name__ == "__main__":
    main()
